# Generated by Django 3.2.6 on 2022-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procode', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('added_on', models.DateTimeField()),
            ],
        ),
    ]
